# Use Case Two - Project Land Area & Benefits Timeseries Analysis

## Load and Prepare Data
Imports, parameters, database connection, and project/ecoregion scope setup.

In [1]:
import getpass
import itertools
import time
from collections import defaultdict
from IPython.display import display
from contextlib import ExitStack

import altair as alt
import numpy as np
import pandas as pd
import polars as pl
import rasterio as rio
from polars import col
from sqlalchemy import create_engine

from cpra.mp.data import read_data

In [ ]:
t0 = time.time()

# MAD Tables - Tables that are defining how projects are linked to model groups and ecoregions 

A_ECOREGION = "gsd.a_ecoregion"
PROJECT_ECOREGION_CROSSWALK = "cma.c_project_ecoregion"
PROJECT_MODEL_GROUP_CROSSWALK = "cma.c_project_model_group"
A_PROJECT = 'cma.a_project'

# RASTER CROSSWALKS
MORPH_TO_ECOREGION_CROSSWALK = r"/ocean/projects/bcs200002p/shared/grids/crosswalks/morph_pixel_v001__ecoregion_v001.tif"

scenario_list = [7, 8]
model_group_id_list = [602, 608, 520]

# FWOA 
fwoa_model_group = 520

# Switch for units 
selected_unit = 'acres' # Other option: 'sq_meters'
valid_units = {"acres", "sq_meters"} 

conversion_factor = 4046.86 if selected_unit == "acres" else 1.0

In [ ]:
# ---------------------------- MPD (MP29) Connection Properties -----------------------------------------------------
# uri = "postgresql://username:password@server:port/mydatabase"
username = getpass.getuser()
password = getpass.getpass("Enter your password: ")
port = "5432"
host = "vm002.bridges2.psc.edu"
db_name = "mpd_dev"
uri = f"postgresql://{username}:{password}@{host}:{port}/{db_name}"
engine = create_engine(uri)

# Note this will be incorporated into cpra.mp.data library

In [4]:
# ---------------------------- Load MAD Tables -----------------------------------------------------
# Load a_ecoregion
query = f"SELECT * FROM {A_ECOREGION}"
a_ecoregion = pl.from_pandas(pd.read_sql(query, engine))

# Load c_project_ecoregion
query = f"SELECT * FROM {PROJECT_ECOREGION_CROSSWALK} WHERE metric_flag = TRUE"
c_project_ecoregion = pl.from_pandas(pd.read_sql(query, engine))

# Load c_project_model_group
query = f"SELECT * FROM {PROJECT_MODEL_GROUP_CROSSWALK}"
c_project_model_group = pl.from_pandas(pd.read_sql(query, engine))

# Load a_project
query = f"SELECT * FROM {A_PROJECT}"
a_project = pl.from_pandas(pd.read_sql(query, engine))

display(a_ecoregion.head())
display(c_project_ecoregion.head())
display(c_project_model_group.head())
display(a_project.head())

shape: (5, 7)
┌──────────────┬──────────────┬─────────────┬─────────────┬────────────┬─────────────┬─────────────┐
│ ecoregion_ui ┆ geom         ┆ ecoregion_c ┆ ecoregion_n ┆ region_uid ┆ ecoregion_d ┆ ecoregion_i │
│ d            ┆ ---          ┆ ode         ┆ ame         ┆ ---        ┆ escription  ┆ d           │
│ ---          ┆ str          ┆ ---         ┆ ---         ┆ f64        ┆ ---         ┆ ---         │
│ i64          ┆              ┆ str         ┆ str         ┆            ┆ str         ┆ i64         │
╞══════════════╪══════════════╪═════════════╪═════════════╪════════════╪═════════════╪═════════════╡
│ 2            ┆ 010600002023 ┆ LBAnw       ┆ Lower       ┆ 2.0        ┆ Barataria   ┆ 12          │
│              ┆ 690000010000 ┆             ┆ Barataria - ┆            ┆ Basin south ┆             │
│              ┆ 000103…      ┆             ┆ northwest   ┆            ┆ of GIWW …   ┆             │
│ 3            ┆ 010600002023 ┆ LBAse       ┆ Lower       ┆ 2.0        ┆ Barataria   ┆ 17          │
│              ┆ 690000010000 ┆             ┆ Barataria - ┆            ┆ Basin from  ┆             │
│              ┆ 000103…      ┆             ┆ southeast   ┆            ┆ the Missi…  ┆             │
│ 4            ┆ 010600002023 ┆ LBAsw       ┆ Lower       ┆ 2.0        ┆ Barataria   ┆ 15          │
│              ┆ 690000020000 ┆             ┆ Barataria - ┆            ┆ Basin       ┆             │
│              ┆ 000103…      ┆             ┆ southwest   ┆            ┆ between     ┆             │
│              ┆              ┆             ┆             ┆            ┆ Bayou …     ┆             │
│ 5            ┆ 010600002023 ┆ MBA         ┆ Mid         ┆ 2.0        ┆ Middle      ┆ 11          │
│              ┆ 690000020000 ┆             ┆ Barataria   ┆            ┆ Barataria   ┆             │
│              ┆ 000103…      ┆             ┆             ┆            ┆ Basin from  ┆             │
│              ┆              ┆             ┆             ┆            ┆ US…         ┆             │
│ 7            ┆ 010600002023 ┆ ATB         ┆ Atchafalaya ┆ 1.0        ┆ Atchafalaya ┆ 26          │
│              ┆ 690000010000 ┆             ┆ Basin       ┆            ┆ River basin ┆             │
│              ┆ 000103…      ┆             ┆             ┆            ┆ upstre…     ┆             │
└──────────────┴──────────────┴─────────────┴─────────────┴────────────┴─────────────┴─────────────┘

shape: (5, 5)
┌───────────────────────┬────────────┬───────────────┬─────────────┬──────────────┐
│ project_ecoregion_uid ┆ project_id ┆ ecoregion_uid ┆ metric_flag ┆ ecoregion_id │
│ ---                   ┆ ---        ┆ ---           ┆ ---         ┆ ---          │
│ i64                   ┆ i64        ┆ i64           ┆ bool        ┆ i64          │
╞═══════════════════════╪════════════╪═══════════════╪═════════════╪══════════════╡
│ 1                     ┆ 60000      ┆ 14            ┆ true        ┆ 9            │
│ 2                     ┆ 60000      ┆ 17            ┆ true        ┆ 7            │
│ 3                     ┆ 60000      ┆ 20            ┆ true        ┆ 6            │
│ 4                     ┆ 130100     ┆ 1             ┆ true        ┆ 13           │
│ 5                     ┆ 130100     ┆ 2             ┆ true        ┆ 12           │
└───────────────────────┴────────────┴───────────────┴─────────────┴──────────────┘

shape: (5, 7)
┌──────────────┬────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────┐
│ project_mode ┆ project_id ┆ model_group_ ┆ cost_model_g ┆ implementati ┆ model_implem ┆ icm_flag │
│ l_group_uid  ┆ ---        ┆ id           ┆ roup_id      ┆ on_period    ┆ entation     ┆ ---      │
│ ---          ┆ i64        ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ bool     │
│ i64          ┆            ┆ i64          ┆ i64          ┆ i64          ┆ str          ┆          │
╞══════════════╪════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════╡
│ 505          ┆ 3490000    ┆ 521          ┆ 626          ┆ 1            ┆ [Implemented ┆ true     │
│              ┆            ┆              ┆              ┆              ┆ in 2025/ICM  ┆          │
│              ┆            ┆              ┆              ┆              ┆ Year …       ┆          │
│ 506          ┆ 3490000    ┆ 626          ┆ 626          ┆ 1            ┆ [Implemented ┆ true     │
│              ┆            ┆              ┆              ┆              ┆ in 2025/ICM  ┆          │
│              ┆            ┆              ┆              ┆              ┆ Year …       ┆          │
│ 507          ┆ 3500000    ┆ 522          ┆ 627          ┆ 1            ┆ Candidates   ┆ false    │
│              ┆            ┆              ┆              ┆              ┆ not chosen   ┆          │
│              ┆            ┆              ┆              ┆              ┆ in Maste…    ┆          │
│ 508          ┆ 3500000    ┆ 627          ┆ 627          ┆ 1            ┆ [Implemented ┆ true     │
│              ┆            ┆              ┆              ┆              ┆ in 2022/ICM  ┆          │
│              ┆            ┆              ┆              ┆              ┆ Year …       ┆          │
│ 509          ┆ 3510000    ┆ 522          ┆ 627          ┆ 1            ┆ Candidates   ┆ false    │
│              ┆            ┆              ┆              ┆              ┆ not chosen   ┆          │
│              ┆            ┆              ┆              ┆              ┆ in Maste…    ┆          │
└──────────────┴────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────┘

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ project_n ┆ project_v ┆ display_i ┆ … ┆ duration_ ┆ solicitat ┆ project_d ┆ legacy_p │
│ d         ┆ umber     ┆ ersion    ┆ d         ┆   ┆ ped_year  ┆ ion_sourc ┆ escriptio ┆ roject_n │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ e         ┆ n         ┆ umber    │
│ i64       ┆ i64       ┆ str       ┆ str       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 510000    ┆ 51        ┆ null      ┆ 051       ┆ … ┆ null      ┆ Unknown   ┆ Marsh     ┆ 001.MC.1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Buffer in ┆ 9        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ front of  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lake …    ┆          │
│ 520000    ┆ 52        ┆ null      ┆ 052       ┆ … ┆ null      ┆ Unknown   ┆ Pass a    ┆ 001.MC.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Loutre    ┆ 3        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Marsh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Creation  ┆          │
│ 530000    ┆ 53        ┆ null      ┆ 053       ┆ … ┆ null      ┆ St.       ┆ Construct ┆ 001.OR.0 │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bernard   ┆ a living  ┆ 1a       │
│           ┆           ┆           ┆           ┆   ┆           ┆ Parish    ┆ breakwate ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Master    ┆ r …       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Plan      ┆           ┆          │
│ 550000    ┆ 55        ┆ null      ┆ 055       ┆ … ┆ null      ┆ CIAP      ┆ Shoreline ┆ 001.SP.0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ protectio ┆ 1        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n through ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ r…        ┆          │
│ 560000    ┆ 56        ┆ null      ┆ 056       ┆ … ┆ null      ┆ Unknown   ┆ assume    ┆ 001.SP.0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ave. H20  ┆ 2        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ depth of  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4 ft.…    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Build the project/model-group scope used by all downstream raster calculations.
# This narrows the analysis to requested model groups and keeps only projects
# that also have valid metric-enabled ecoregion mappings in the crosswalk table.

filtered_project_model_group = c_project_model_group.filter(
    (col("model_group_id").is_in(model_group_id_list))
).join(c_project_ecoregion, on="project_id", how="inner")

# Keep one row per (model_group_id, project_id) pair for a quick validation view.
# Joins can contain multiple rows per project due to ecoregion granularity;
# this deduplicated table makes it easy to confirm coverage before heavy processing.
unique_pairings_df = filtered_project_model_group.unique(
    subset=["model_group_id", "project_id"]
).sort(["model_group_id", "project_id"])

unique_pairings_df.select(["model_group_id", "project_id"])

shape: (4, 2)
┌────────────────┬────────────┐
│ model_group_id ┆ project_id │
│ ---            ┆ ---        │
│ i64            ┆ i64        │
╞════════════════╪════════════╡
│ 602            ┆ 1230000    │
│ 602            ┆ 2440000    │
│ 608            ┆ 1390000    │
│ 608            ┆ 2520000    │
└────────────────┴────────────┘

In [ ]:
# Build all scenario/model-group combinations that will be processed.

scenario_model_group = list(itertools.product(scenario_list, model_group_id_list))
display(scenario_model_group)

# For each (scenario, model_group), fetch annual land-type raster paths 
# read_data query returns tif paths to the 50 years of model data in the form of a lazyframe 

scenario_model_group_dict = {
    (scenario, model_group_id): read_data(
        variable="lnd_type",
        grid="morph_pixel_v001",
        time_unit="annual",
        model_group_id=model_group_id,
        scenario_id=scenario,
    ).select(["calendar_year", "path"])
    for scenario, model_group_id in scenario_model_group
}

# structure =  {
#     (scenario, model_group_id) : pl.LazyFrame
# }

# Materialize year->path dict per (scenario, model_group) from lazyframes to the appropriate scenario model group for selection during windowed analysis 
# Downstream raster loops need a year -> filepath mapping for windowed reads.

tif_by_modelgroup_scenario_year = {
    my_tuple: dict(select_lazyframe.collect().iter_rows())
    for my_tuple, select_lazyframe in scenario_model_group_dict.items()
}

# structure =  {
#     (scenario, model_group_id) : {year : tif_path}
# }

[(7, 602), (7, 608), (7, 520), (8, 602), (8, 608), (8, 520)]

{(7, 602): <LazyFrame at 0x151292A77C80>,
 (7, 608): <LazyFrame at 0x1512933549E0>,
 (7, 520): <LazyFrame at 0x151291D43350>,
 (8, 602): <LazyFrame at 0x151291DB4290>,
 (8, 608): <LazyFrame at 0x151291DB4950>,
 (8, 520): <LazyFrame at 0x151291DB4680>}

shape: (52, 2)
┌───────────────┬─────────────────────────────────┐
│ calendar_year ┆ path                            │
│ ---           ┆ ---                             │
│ i32           ┆ str                             │
╞═══════════════╪═════════════════════════════════╡
│ 2019          ┆ /ocean/projects/bcs200002p/sha… │
│ 2020          ┆ /ocean/projects/bcs200002p/sha… │
│ 2021          ┆ /ocean/projects/bcs200002p/sha… │
│ 2022          ┆ /ocean/projects/bcs200002p/sha… │
│ 2023          ┆ /ocean/projects/bcs200002p/sha… │
│ …             ┆ …                               │
│ 2066          ┆ /ocean/projects/bcs200002p/sha… │
│ 2067          ┆ /ocean/projects/bcs200002p/sha… │
│ 2068          ┆ /ocean/projects/bcs200002p/sha… │
│ 2069          ┆ /ocean/projects/bcs200002p/sha… │
│ 2070          ┆ /ocean/projects/bcs200002p/sha… │
└───────────────┴─────────────────────────────────┘

dict_keys([(7, 602), (7, 608), (7, 520), (8, 602), (8, 608), (8, 520)])

In [7]:
# Build distinct (model_group, project, ecoregion) mappings from the filtered crosswalk.
# Downstream raster counting needs valid ecoregions associated with each model group.

subset_project_model_ecoregion_df = filtered_project_model_group.unique(
    subset=["model_group_id", "project_id", "ecoregion_id"]
).select(["model_group_id", "project_id", "ecoregion_id"])

# Collapse to one row per model group with a list of ecoregion IDs.
# This structure supports per-model-group masking during raster window loops.
project_model_ecoregion_df = subset_project_model_ecoregion_df.group_by(
    "model_group_id", maintain_order=True
).agg(col("ecoregion_id"))

project_model_ecoregion_df

shape: (2, 2)
┌────────────────┬────────────────┐
│ model_group_id ┆ ecoregion_id   │
│ ---            ┆ ---            │
│ i64            ┆ list[i64]      │
╞════════════════╪════════════════╡
│ 602            ┆ [12, 21, … 1]  │
│ 608            ┆ [20, 21, … 23] │
└────────────────┴────────────────┘

## Raster Window Analysis
Windowed raster reads and per-ecoregion land-pixel aggregation, followed by area/benefit calculations.

In [ ]:
t1 = time.time()

# Determine what ecoregions are allowed for each model group and store in a dictionary of ecoregion id arrays by model group id 

ecoregion_by_model_group_dict = {}
all_ecoregion_ids = np.unique(project_model_ecoregion_df.get_column("ecoregion_id").explode())

for model_group in model_group_id_list:
    # FWOA uses all mapped ecoregions; project model groups use only their mapped subset.
    if model_group == fwoa_model_group:
        ecoregion_by_model_group_dict[model_group] = all_ecoregion_ids
    else:
        ecoregion_by_model_group_dict[model_group] = np.array(
            project_model_ecoregion_df
            .filter(col("model_group_id") == model_group)
            .get_column("ecoregion_id")
            .item()
        )

# Accumulate windows and the common ecoregion ids found per model group

window_by_model_group_dict = defaultdict(list)

with rio.open(MORPH_TO_ECOREGION_CROSSWALK) as index_src:
    # Pixel area in square meters from raster resolution.
    pixel_width, pixel_height = index_src.res
    pixel_area = abs(pixel_width * pixel_height)

    for block_index, window in index_src.block_windows(1):
        ecoregion_ids = index_src.read(1, window=window)

        for model_group_id in model_group_id_list:
            ecoregion_array = ecoregion_by_model_group_dict[model_group_id]
            mask = np.isin(ecoregion_ids, ecoregion_array)
            if not mask.any():
                continue
            
            common_ecoregion_ids = np.where(mask, ecoregion_ids, -9999) # -9999 is the mask sentinel value

            window_by_model_group_dict[model_group_id].append((window, common_ecoregion_ids))


# Accumulate land-pixel counts keyed by (scenario, model_group, year, ecoregion).

pixel_counts = defaultdict(int)

for (scenario, model_group_id), lnd_type_dict in tif_by_modelgroup_scenario_year.items():

    model_group_windows = window_by_model_group_dict[model_group_id]

    # print(f"For model group {model_group_id} and scenario {scenario}, the ecoregions are {ecoregion_array}")

    with ExitStack() as stack:
        year_src = {year: stack.enter_context(rio.open(tif))
                    for year, tif in lnd_type_dict.items()}
        
        for window, common_ecoregion_ids in model_group_windows:
            # For each year, count land pixels (excluding water=2 and nodata=-9999).
            for year, src in year_src.items():
                # with rio.open(src) as land_type_values:
                land_type_window = src.read(1, window=window)
                land_mask = (land_type_window != 2) & (land_type_window != -9999)
                land_ecoregion_pixels = common_ecoregion_ids[land_mask]

                valid_land_ecoregion_pixels = land_ecoregion_pixels[land_ecoregion_pixels != -9999]
                if valid_land_ecoregion_pixels.size == 0:
                    continue

                unique_ids, counts = np.unique(valid_land_ecoregion_pixels, return_counts=True)

                # Aggregate counts into the scenario/model_group/year/ecoregion key.
                for eco_id, count in zip(unique_ids, counts):
                        key = (scenario, model_group_id, int(year), int(eco_id))
                        pixel_counts[key] += int(count)

# Convert accumulator dict into row records for DataFrame creation in the next cell.
records = [
    {
        'scenario':k[0],
        'model_group_id':k[1],
        'year':k[2],
        'ecoregion_id':k[3],
        'land_pixel_count':v,
    }
    for k,v in pixel_counts.items()
]

t2 = time.time()
 
print(f"Total Run Time for Windowed Analysis: {t2 - t1}")

Total Run Time for Windowed Analysis: 58.14012169837952

In [ ]:
# Convert aggregated pixel-count records into a tabular frame for downstream joins/calculations.
land_area_df = pl.DataFrame(records)

# Split project runs (FWA) from the baseline run (FWOA model group 520).
fwp_land_area = land_area_df.filter(col("model_group_id") != fwoa_model_group)
fwoa_land_area = land_area_df.filter(col("model_group_id") == fwoa_model_group)

# Attach baseline counts by matching on shared dimensions (ecoregion, year, scenario).
joined_land_area = fwp_land_area.join(
    fwoa_land_area, 
    on=["ecoregion_id", "year", "scenario"], how="left", suffix="_FWOA"
)

# Map ecoregion/model-group totals back to project_id, then aggregate to project-year level.
joined_df = (
    joined_land_area.join(
        filtered_project_model_group,
        left_on=["ecoregion_id", "model_group_id"],
        right_on=["ecoregion_id", "model_group_id"],
        how="inner",
        suffix="_crosswalk",
    )
    .group_by(["project_id", "scenario", "model_group_id", "year"])
    .agg([col("land_pixel_count").sum(), col("land_pixel_count_FWOA").sum()])
    .sort("model_group_id")
)

# Benefit area = project scenario land area minus baseline land area (in native square meters).
difference_area_exp = (
    (col("land_pixel_count") - col("land_pixel_count_FWOA")) * pixel_area
)

# Validate units; if invalid, default to square meters to avoid bad conversions.
if selected_unit not in valid_units:
    print(
        f"'{selected_unit}' is not valid, falling back to square meters. Valid options: {sorted(valid_units)}"
    )
    selected_unit = 'sq_meters'

difference_area_exp = (
    (col("land_pixel_count") - col("land_pixel_count_FWOA")) * pixel_area
) / conversion_factor

# Dynamic output column names aligned to the selected unit.
col_name = "project_benefit_acres" if selected_unit == "acres" else "project_benefit_sq_meters"

# Total project land area in the selected unit.
land_area_exp = col('land_pixel_count') * pixel_area / conversion_factor
land_col_name = "project_land_area_acres" if selected_unit == 'acres' else "project_land_area_sq_meters"

# Add both derived metrics to the project-level results table.
joined_df = joined_df.with_columns(
    difference_area_exp.alias(col_name),
    land_area_exp.alias(land_col_name)
)

## Visualization and Outputs
Time-series shaping and chart configuration.

In [10]:
# Reshape analysis output into plotting-friendly columns.
df_plot = joined_df.with_columns(
    (
        # Unique line identifier: one series per project-model-scenario combination.
        pl.concat_str(
            [col("project_id"), col("model_group_id"), col("scenario")], separator="_"
        ).alias("id")
    ),
    (
        # Facet label used in the chart panel titles.
        pl.concat_str(
            [col("project_id").cast(pl.Utf8), col("model_group_id").cast(pl.Utf8)],
            separator=" | ",
        ).alias("project_model")
    ),
    # Represent annual values at year-end so Altair uses a true temporal axis.
    (pl.datetime(col("year"), 12, 31).alias("yr")),
).sort(["project_model", "id", "yr"])

df_plot.head(2)

shape: (2, 11)
┌────────────┬──────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ project_id ┆ scenario ┆ model_grou ┆ year ┆ … ┆ project_la ┆ id         ┆ project_mo ┆ yr        │
│ ---        ┆ ---      ┆ p_id       ┆ ---  ┆   ┆ nd_area_ac ┆ ---        ┆ del        ┆ ---       │
│ i64        ┆ i64      ┆ ---        ┆ i64  ┆   ┆ res        ┆ str        ┆ ---        ┆ datetime[ │
│            ┆          ┆ i64        ┆      ┆   ┆ ---        ┆            ┆ str        ┆ μs]       │
│            ┆          ┆            ┆      ┆   ┆ f64        ┆            ┆            ┆           │
╞════════════╪══════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 1230000    ┆ 7        ┆ 602        ┆ 2019 ┆ … ┆ 287993.950 ┆ 1230000_60 ┆ 1230000 |  ┆ 2019-12-3 │
│            ┆          ┆            ┆      ┆   ┆ 866        ┆ 2_7        ┆ 602        ┆ 1         │
│            ┆          ┆            ┆      ┆   ┆            ┆            ┆            ┆ 00:00:00  │
│ 1230000    ┆ 7        ┆ 602        ┆ 2020 ┆ … ┆ 287604.760 ┆ 1230000_60 ┆ 1230000 |  ┆ 2020-12-3 │
│            ┆          ┆            ┆      ┆   ┆ 234        ┆ 2_7        ┆ 602        ┆ 1         │
│            ┆          ┆            ┆      ┆   ┆            ┆            ┆            ┆ 00:00:00  │
└────────────┴──────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [11]:
# Build a project-to-ecoregion-code lookup table for chart/table context.
ecoregion_names = subset_project_model_ecoregion_df.select(['project_id', 'ecoregion_id']).join(
    # Attach short ecoregion codes (e.g., BA, TE) from MAD reference data.
    a_ecoregion.select(['ecoregion_code', 'ecoregion_id']),
    on='ecoregion_id',
    how='left'
).join(
    # Attach human-readable project names.
    a_project.select(['project_id', 'project_name']),
    on='project_id',
    how='left'
).select(['project_name', 'ecoregion_code'])

# Collapse to one row per project with a list of associated ecoregion codes.
ecoregion_names = ecoregion_names.group_by(
    "project_name", maintain_order=True
).agg(col("ecoregion_code"))

In [12]:
# Convert Polars to pandas because Altair expects pandas-like tabular input.
df_plot_pd = df_plot.to_pandas()

# Dropdown parameter that lets users switch between benefit and land-area metrics.
metric_param = alt.param(
    name="metric_sel",
    value=col_name,
    bind=alt.binding_select(
        options=[col_name, land_col_name],
        labels=["Project Benefit", "Land Area"],
        name="View: ",
    ),
)

# Enable pan/zoom interaction on each faceted chart.
zoom_pan = alt.selection_interval(bind="scales")

# Scenario color mapping (solid lines):
# - FWA Low Scenario  -> #9FCC3B
# - FWA High Scenario -> #5E8021
scenario_color_scale = alt.Scale(
    domain=[7, 8],  
    range=["#9FCC3B", "#5E8021"],
)

# Build a single chart pipeline for both metrics by folding wide columns to long form.
# Then filter to the currently selected metric from the dropdown.
base = (
    alt.Chart(df_plot_pd)
    .transform_fold(
        [col_name, land_col_name],
        as_=["metric", "value"],
    )
    .transform_filter(alt.datum.metric == metric_param)
    .encode(
        x=alt.X("yr:T", title="Year"),
        y=alt.Y("value:Q", title=f"Area ({selected_unit})"),
        color=alt.Color(
            "scenario:N",
            title="Scenario",
            scale=scenario_color_scale,
        ),
        detail=alt.Detail("id:N"),
        tooltip=[
            "project_id:N",
            "model_group_id:N",
            "scenario:N",
            "id:N",
            "yr:T",
            "metric:N",
            "value:Q",
        ],
    )
)

# Main lines plus a faint zero reference line for context.
lines = base.mark_line(point=False)
zero_line = alt.Chart(df_plot_pd).mark_rule(color="gray", size=0.5, opacity=0.1).encode(y=alt.datum(0))

# Dynamic title updates based on which metric is selected in the dropdown.
dynamic_title = alt.TitleParams(
    text=alt.ExprRef(
        expr=(
            f"metric_sel == '{col_name}' "
            "? 'Total Project Benefit (FWA-FWOA) - Time Series Analysis' "
            ": 'Total Project Land Area - Time Series Analysis'"
        )
    ),
    anchor="middle",
    font='Franklin Gothic Book',
    fontSize=20,
    subtitle=f"Model Groups 608 and 602, FWOA Model Used: {fwoa_model_group}",
    subtitleFontSize=14,
)

# Assemble layered + faceted interactive chart.
chart = (
    alt.layer(lines, zero_line, data=df_plot_pd)
    .add_params(metric_param, zoom_pan)
    .facet(
        facet=alt.Facet("project_model:N", title="Project | Model Group"),
        columns=2,
    )
    .resolve_scale(x="independent")
    .properties(title=dynamic_title)
)

with pl.Config(tbl_rows=-1, tbl_cols=-1, fmt_str_lengths=1000):
    display(ecoregion_names)

chart

shape: (4, 2)
┌─────────────────────────────────────────┬───────────────────────────┐
│ project_name                            ┆ ecoregion_code            │
│ ---                                     ┆ ---                       │
│ str                                     ┆ list[str]                 │
╞═════════════════════════════════════════╪═══════════════════════════╡
│ Union Freshwater Diversion              ┆ ["LBAnw", "LPO", … "MRP"] │
│ Increase Atchafalaya Flow to Terrebonne ┆ ["VRT", "ETB", … "PEN"]   │
│ Belle Pass-Golden Meadow Marsh Creation ┆ ["ETB", "LBAsw"]          │
│ St. Tammany Marsh Creation              ┆ ["LPO"]                   │
└─────────────────────────────────────────┴───────────────────────────┘

alt.FacetChart(...)

In [13]:
t3 = time.time()
print(f"Total Run Time for Analysis: {t3 - t0}")

Total Run Time for Analysis: 64.82855272293091